platform :ios, '10.0'
use_frameworks!

target 'Chef' do
    pod 'SnapKit'
    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Kingfisher'

end
